name: Agify API Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node required
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:api